arch: s390x
services:
  - docker
script: docker login quay.io -u $ROBOT_USER -p $ROBOT_TOKEN && docker build stable/alpine/Dockerfile --tag quay.io/ibmz/docker-nginx && docker push quay.io/ibmz/docker-nginx
